Manual payment
dIB59/hello pull request #24
Opened 2024-10-09 10:55 UTC by aswathikb

Implemented manual payment system with stripe.

2024-10-09 15:38 UTC, dIB59 requested changes
Please add tests, Stripe exposes endpoint specifically for testing.
Share the API keys with me as well. (DM on pumble)

2024-10-09 15:38 UTC, dIB59 commented on webserver/src/handlers/stripe_handler.rs
> +        }
Do not print.
Use log::error instead

2024-10-09 15:38 UTC, dIB59 commented on webserver/src/handlers/stripe_handler.rs
> +        }
Use log::error

2024-10-09 15:38 UTC, dIB59 commented on webserver/src/handlers/stripe_handler.rs
> +        }
Use log::error

2024-10-09 15:38 UTC, dIB59 commented on webserver/src/handlers/stripe_handler.rs
> +        web::scope("/api")
Do we need scope api here?

2024-10-10 09:38 UTC, dIB59 commented on webserver/src/handlers/stripe_handler.rs
> +        }
Please use the correct error message. Should be [502 Bad Gateway](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502)

2024-10-15 09:52 UTC, dIB59 commented on webserver/src/services/stripe_service.rs
pub struct PaymentService {
    client: Client,
    base_url: String,
}

impl PaymentService {
    // Constructor for PaymentService with injected base_url
    pub fn new(client: Client, base_url: String) -> Self {
        PaymentService {
            client,
            base_url,
        }
    }

    // Method for creating a payment
    pub async fn create_payment(
        &self,
        amount: u64,
        currency: &str,
    ) -> Result<PaymentIntentResponse, reqwest::Error> {
        let api_key = std::env::var("STRIPE_SECRET_KEY").expect("STRIPE_SECRET_KEY must be set");

        let payment_intent = CreatePaymentRequest {
            amount,
            currency: currency.to_string(),
            payment_method_types: vec!["card".to_string()],
        };

        let res = self.client
            .post(format!("{}/v1/payment_intents", self.base_url))  // Use base_url from the struct
            .bearer_auth(api_key)
            .json(&payment_intent)
            .send()
            .await?
            .json::<PaymentIntentResponse>()
            .await?;

        Ok(res)
    }
}

2024-10-15 09:53 UTC, dIB59 commented on webserver/src/services/stripe_service.rs
This would be a better way of doing this, as it will not require checking to see if there a test occuring

2024-10-22 07:52 UTC, dIB59 commented
None of the tests actually test stripe payments. Please update tests to make sure you are able to purchase things.

2024-11-13 15:38 UTC, Annmaryjoppan approved these changes

2024-11-30 12:53 UTC, closed without merging