Implement S3 file upload API route
dIB59/hello pull request #7
Opened 2024-09-19 10:02 UTC by stefanpython

This PR adds a new API route for handling file uploads to AWS S3.

Key changes:
- Implement `uploadFileToS3` function to manage S3 uploads
- Add POST route for file validation and upload
- Implement file type checking for images
- Ensure correct content type is passed to S3

Testing:
- [ ] Tested file uploads with various image types
- [ ] Verified S3 upload functionality
- [ ] Checked error handling for invalid file types

Please review and let me know if any changes are needed.

2024-09-20 09:03 UTC, dIB59 requested changes
Take a look at the docs
https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment

2024-09-20 09:03 UTC, dIB59 commented on frontend/app/api/s3-upload/route.ts
> +import { NextResponse } from "next/server";
Make this file server only, to avoid unintended client usage of server code

2024-09-20 09:46 UTC, stefanpython commented on frontend/app/api/s3-upload/route.ts
> +        accessKeyId: process.env.NEXT_PUBLIC_AWS_S3_ACCESS_KEY_ID as string,
Made variables private and installed server-only packaged for extra security layer

2024-09-20 09:49 UTC, stefanpython commented
> Take a look at the docs https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment

Thank you for the support and for providing me with the docs. I appreciate it.

2024-09-23 13:48 UTC, dIB59 approved these changes
LGTM

2024-09-24 08:34 UTC, merged