feature: Implementing chat authentication
dIB59/hello pull request #9
Opened 2024-09-20 11:22 UTC by kimz95

2024-09-20 12:45 UTC, dIB59 requested changes
When please use match statements, look at the rust way of doing things

2024-09-20 12:45 UTC, dIB59 commented on webserver/src/chat/mod.rs
> +        }
Return only a single error, just say unauthorized. No reason to state anything else.

2024-09-20 12:45 UTC, dIB59 commented on webserver/src/chat/mod.rs
> +                            name: None,
Name should not be none, it should be the user name.

2024-09-20 13:38 UTC, kimz95 commented
> When please use match statements, look at the rust way of doing things

Should I use nested match statements in cases like these or is better to use 'unwrap_or' for error handling? because I seem to find contradicting things online about best practices

2024-09-25 08:25 UTC, dIB59 approved these changes
LGTM

2024-09-25 08:48 UTC, closed without merging